name: Version and Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update version
      run: |
        # Update version in all packages
        cd packages/shared
        npm version ${{ github.event.inputs.version_type || 'patch' }} --no-git-tag-version
        
        cd ../server
        npm version ${{ github.event.inputs.version_type || 'patch' }} --no-git-tag-version
        
        cd ../standalone
        npm version ${{ github.event.inputs.version_type || 'patch' }} --no-git-tag-version
        
    - name: Commit and tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add packages/*/package.json
        git commit -m "chore: bump version"
        git tag "v$(node -p "require('./packages/standalone/package.json').version")"
        git push origin main --tags